import { Category, ContentSection } from '@/types';

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Información General',
    slug: 'general-information',
    icon: 'Info',
    order_index: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Habitaciones',
    slug: 'rooms',
    icon: 'BedDouble',
    order_index: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Restaurantes & Bares',
    slug: 'restaurants-bars',
    icon: 'UtensilsCrossed',
    order_index: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Casino',
    slug: 'casino',
    icon: 'Dice5',
    order_index: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Instalaciones',
    slug: 'facilities',
    icon: 'Waves',
    order_index: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Eventos & Convenciones',
    slug: 'events-conventions',
    icon: 'CalendarDays',
    order_index: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Bodas',
    slug: 'weddings',
    icon: 'Heart',
    order_index: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockContentSections: Record<string, ContentSection[]> = {
  '1': [
    {
      id: 'section-1',
      category_id: '1',
      title: 'Información del Hotel',
      slug: 'hotel-info',
      content: {
        hotel_name: 'Santo Domingo Bay',
        category: '4 estrellas',
        location: 'Boca Chica, República Dominicana',
        address: 'Calle Caracol 1, Boca Chica 15700',
        phone: '+1 809 523 4611',
        email: 'info@sdbhotel.com',
        website: 'https://santodomingobay.com',
      },
      order_index: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'section-2',
      category_id: '1',
      title: 'Horarios',
      slug: 'hours',
      content: {
        checkin: '15:00',
        checkout: '12:00',
        reception_24h: true,
      },
      order_index: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  '3': [
    {
      id: 'section-3',
      category_id: '3',
      title: 'La Famiglia',
      slug: 'la-famiglia',
      content: {
        name: 'La Famiglia',
        type: 'Restaurante Italiano',
        location: 'Main Building',
        concept: 'Inspirado en la tradición familiar italiana',
        specialties: ['Pasta fresca', 'Pizzas artesanales', 'Vino'],
        ambiance: 'Cálido y acogedor',
      },
      order_index: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'section-4',
      category_id: '3',
      title: 'KIBO',
      slug: 'kibo',
      content: {
        name: 'KIBO',
        type: 'Restaurante Asiático',
        location: 'Rooftop',
        concept: 'Fusión asiática con vistas panorámicas',
        cuisine: ['Japonés', 'Tailandés', 'Chino'],
        features: ['Vista 360°', 'Sunset dining', 'Cocktails asiáticos'],
      },
      order_index: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};
